---
title: "StatInference_Project - Part B"
author: "Georgia P"
date: "September 14, 2015"
output: pdf_document
---
#Overview
In this analysis the goal is analyze growth data for teeth (ToothGrowth Data) and explore statistical significance of evolution measured as **Tooth Length** (len variable) as well as the correlation with parameters such as **Supplement type** (VC or OJ) (supp variable) and **Dose in milligrams** (dose variable).

#Exloratory analysis
```{r qplot echo=TRUE, message=FALSE} 
library(datasets) ; library(ggplot2)
tdata<-ToothGrowth
#basic summary of dataset
summary(tdata)

# plot densities
qplot(data=tdata, x=len, color= supp,geom="density",  facets=. ~ dose, xlab = "length per dose category", main="Length density per dose and supplement types", labels="supplement type")

```
Load the ToothGrowth data and perform some basic exploratory data analyses 
Provide a basic summary of the data.
Use confidence intervals and/or hypothesis tests to compare tooth growth by supp and dose. (Only use the techniques from class, even if there's other approaches worth considering)
State your conclusions and the assumptions needed for your conclusions. 

Some criteria that you will be evaluated on
Did you  perform an exploratory data analysis of at least a single plot or table highlighting basic features of the data?
Did the student perform some relevant confidence intervals and/or tests?
Were the results of the tests and/or intervals interpreted in the context of the problem correctly? 
Did the student describe the assumptions needed for their conclusions?